let mock = [{
    id: 1,
    name: "Lemon Meringue Cheesecake",
    ingredients: ["2 cups shortbread cookie crumbs", "¼ cup melted butter", "3 (8 ounce) packages cream cheese, softened", "1 cup sour cream", "1 cup white sugar", "4 eggs", "¼ cup fresh lemon juice", "1 teaspoon vanilla extract", "1 lemon, zested"],
    time: "5 hrs 30 mins",
    calories: "7728 cals",
    category: "Dessert",
    image: '1.jpg'
  },
  {
    id: 2,
    name: "Lemon Ricotta Cake",
    ingredients: ["1 ½ cups cake flour", "1 teaspoon baking powder", "1 teaspoon baking soda", "¼ teaspoon salt", "1 cup white sugar", "¾ cup butter, softened", "1 (15 ounce) container whole-milk ricotta cheese", "1 lemon, juiced and zested"],
    time: "4 hrs 20 mins",
    calories: "6290 cals",
    category: "Dessert",
    image: "2.jpg",
  },
  {
    id: 3,
    name: "Spicy and Tender Corned Beef",
    ingredients: ["1/2 (12 fluid ounce) can or bottle dark beer", "1 tablespoon dry mustard", "1 pinch salt and ground black pepper", "3 whole cloves" , "1 (16 ounce) package carrots", "1 (16 ounce) package small red potatoes", "1 head green cabbage"],
    time: "1 hrs 10 mins",
    calories: "1200 cals",
    category: "Entree",
    image: "3.jpg",
  },
  {
    id: 4,
    name: "Low-Carb Salisbury Steak",
    ingredients: ["2 pounds ground beef", "1 onion", "diced 2 eggs", "1 tablespoon Worcestershire sauce", "1 tablespoon dried parsley flakes", "2 teaspoons salt1/2 teaspoon garlic powder"],
    time: "3 hrs 20 mins",
    calories: "1780 cals",
    category: "Entree",
    image: "4.jpg",
  },
  {
    id: 5,
    name: "Beef and Vegetable Stew",
    ingredients: ["1 pound cubed beef stew meat", "1 tablespoon vegetable oil1 onion", "sliced 1 (6 ounce) can tomato paste", "1 (14.5 ounce) can beef broth", "1 cup chopped carrots", "3 potatoes", "1 sprig fresh rosemary"],
    time: "2 hrs 30 mins",
    calories: "2800 cals",
    category: "Entree",
    image: "5.jpg",
  },
  {
    id: 6,
    name: "St. Patrick's Day Jell-O Shots",
    ingredients: ["1 pound cubed beef stew meat", "1 tablespoon vegetable oil1 onion", "sliced 1 (6 ounce) can tomato paste", "1 (14.5 ounce) can beef broth", "1 cup chopped carrots", "3 potatoes", "1 sprig fresh rosemary"],
    time: "1 hrs 00 mins",
    calories: "400 cals",
    category: "Drink",
    image: "6.jpg",
  },
  {
    id: 7,
    name: "Classic Macaroni Salad",
    ingredients: ["4 cups uncooked elbow macaroni", "1 cup mayonnaise", "1/4 cup distilled white vinegar", "2/3 cup white sugar", "1/2 tablespoons yellow mustard", "1/2 teaspoon ground black pepper", "1 large onion"],
    time: "1 hrs 10 mins",
    calories: "1500 cals",
    category: "Appetizer",
    image: "7.jpg",
  },
  {
    id: 8,
    name: "King Crab Appetizers",
    ingredients: ["2 (12 ounce) packages refrigerated biscuit dough", "1 (8 ounce) package cream cheese", "1 (6 ounce) can crab meat", "2 tablespoons mayonnaise", "2 tablespoons grated Parmesan cheese"],
    time: "1 hrs 00 mins",
    calories: "800 cals",
    category: "Appetizer",
    image: "8.jpg",
  },
  {
    id: 9,
    name: "The Best Potato Salad",
    ingredients: ["6 eggs", "10 red potatoes", "1 cup mayonnaise", "1/2 cup ranch dressing", "1/3 cup dill pickle relish", "2 tablespoons prepared yellow mustard", "1.5 teaspoons salt"],
    time: "1 hrs 13 mins",
    calories: "2800 cals",
    category: "Appetizer",
    image: "9.jpg",
  },
  {
    id: 10,
    name: "Easiest Pot Roast Ever",
    ingredients: ["3 pounds beef roast", "6 potatoes", "1.5 cups baby carrots", "1 yellow onion", "2 stalks celery", "3 cubes beef bouillon", "1/2 cup water"],
    time: "2 hrs 30 mins",
    calories: "2100 cals",
    category: "Entree",
    image: "10.jpg",
  },
]
export default mock;
